### PR TITLE
Fix/runtime translation

### LINKED ISSUE #3443: Localization entries are not applied completely
**Describe the bug**
Not all translations are applied immediately after switching the language.

**To Reproduce**
For the following steps it is assumed the ui language is set to 'English'.
1. Start Tiled
2. Open Preferences menu (Edit > Preferences)
3. Switch to 'Interface'
4. Select a language different than 'English' (best one with an (almost) complete translation)

Result: Most texts are changed, but not all. (See image below)

**Expected behavior**
All texts are changed.

**Media**
tiled_directlyAfterSettingLanguage
Left side: How it looks directly after changing the language
Right side: After restarting Tiled with the correct display

**Specifications:**
 - OS: Windows 11
 - Tiled Version: 1.9.0

### PR DESCRIPTION
**Pull request by SIDDHAARTHAA**
Fixes runtime language-switch gaps where some UI strings only updated after restart.

Added missing `LanguageChange` / `Preferences::languageChanged` retranslation hooks in affected widgets, models, and action handlers, and refreshed dynamic property labels in `PropertiesWidget`.

closes #3443

### CODE REVIEW

File: src/tiled/brokenlinks.cpp [hunk 1]
```diff
@@ -99,6 +101,13 @@ BrokenLinksModel::BrokenLinksModel(QObject *parent)
     : QAbstractListModel(parent)
     , mDocument(nullptr)
 {
+    connect(Preferences::instance(), &Preferences::languageChanged,
+            this, [this] {
+                emit headerDataChanged(Qt::Horizontal, 0, 2);
+
+                if (rowCount() > 0)
+                    emit dataChanged(index(0, 2), index(rowCount() - 1, 2));
+            });
```
Comment (bjorn) [inline src/tiled/brokenlinks.cpp]: I'd like to avoid direct connections to `Preferences::languageChanged` when possible, because the `QEvent::LanguageChange` allows responding to this in a less dependent way. For `BrokenLinksModel`, we can add a `BrokenLinksModel::languageChanged` and call it from `BrokenLinksWidget::changeEvent`.

File: src/tiled/commanddatamodel.cpp [hunk 2]
```diff
@@ -37,6 +37,15 @@ static const char *commandMimeType = "application/x-tiled-commandptr";
...
 {
+    connect(Preferences::instance(), &Preferences::languageChanged,
+            this, [this] {
+                emit headerDataChanged(Qt::Horizontal, 0, 2);
+
+                const int rows = rowCount();
+                const int columns = columnCount();
+                if (rows > 0 && columns > 0)
+                    emit dataChanged(index(0, 0), index(rows - 1, columns - 1));
+            });
```
Comment (bjorn) [inline src/tiled/commanddatamodel.cpp]: Here too, please introduce `CommandDataModel::languageChanged` and call it from the `CommandsEdit`, which as a widget will receive the `QEvent::LanguageChange`.

Also, while you're at it, could you remove the unused `CommandDataModel` instance from `CommandManager`? I seem to have forgotten it in a refactor.

File: src/tiled/commandmanager.cpp [hunk 3]
```diff
@@ -78,6 +78,8 @@ CommandManager::CommandManager()
 
     connect(ProjectManager::instance(), &ProjectManager::projectChanged,
             this, &CommandManager::updateActions);
+    connect(preferences, &Preferences::languageChanged,
+            this, &CommandManager::retranslateUi);
```
Comment (bjorn) [inline src/tiled/commandmanager.cpp]: This function is already called from `MainWindow::retranslateUi`.

File: src/tiled/layermodel.cpp [hunk 4]
```diff
@@ -44,6 +45,11 @@ LayerModel::LayerModel(QObject *parent):
 {
     mTileLayerIcon.addFile(QLatin1String(":images/32/layer-tile.png"));
     mObjectGroupIcon.addFile(QLatin1String(":images/32/layer-object.png"));
+
+    connect(Preferences::instance(), &Preferences::languageChanged,
+            this, [this] {
+                emit headerDataChanged(Qt::Horizontal, 0, 2);
+            });
```
Comment (bjorn) [inline src/tiled/layermodel.cpp]: Please trigger this from `LayerView` based on `QEvent::LanguageChange`.

File: src/tiled/locatorwidget.cpp [hunk 5]
```diff
@@ -323,6 +324,16 @@ void LocatorWidget::setVisible(bool visible)
     }
 }
 
+void LocatorWidget::changeEvent(QEvent *event)
+{
+    QFrame::changeEvent(event);
+
+    if (event->type() == QEvent::LanguageChange) {
+        mFilterEdit->setPlaceholderText(mLocatorSource->placeholderText());
+        setFilterText(mFilterEdit->text());
```
Comment (bjorn) [inline src/tiled/locatorwidget.cpp]: I think we don't need this in the `LocatorWidget` because it is a popup and as such it's not possible to change the language while it is open. Or did you notice a string failing to update here?

File: src/tiled/mapdocumentactionhandler.cpp [hunk 6]
```diff
@@ -235,6 +236,9 @@ MapDocumentActionHandler::MapDocumentActionHandler(QObject *parent)
 
     updateActions();
     retranslateUi();
+
+    connect(Preferences::instance(), &Preferences::languageChanged,
+            this, &MapDocumentActionHandler::retranslateUi);
```
Comment (bjorn) [inline src/tiled/mapdocumentactionhandler.cpp]: This is already called from `MainWindow::retranslateUi`.

File: src/tiled/mapobjectmodel.cpp [hunk 7]
```diff
@@ -81,6 +82,11 @@ MapObjectModel::MapObjectModel(QObject *parent)
     , mObjectGroupIcon(QLatin1String(":/images/16/layer-object.png"))
 {
     mObjectGroupIcon.addFile(QLatin1String(":images/32/layer-object.png"));
+
+    connect(Preferences::instance(), &Preferences::languageChanged,
+            this, [this] {
+                emit headerDataChanged(Qt::Horizontal, 0, ColumnCount - 1);
+            });
```
Comment (bjorn) [inline src/tiled/mapobjectmodel.cpp]: Please trigger this from `ObjectsView` (or `ObjectsDock`) based on `QEvent::LanguageChange`.

File: src/tiled/newversiondialog.cpp [hunk 8]
```diff
@@ -67,6 +65,24 @@ NewVersionDialog::~NewVersionDialog()
     delete ui;
 }
 
+void NewVersionDialog::changeEvent(QEvent *event)
+{
+    QDialog::changeEvent(event);
+
+    if (event->type() == QEvent::LanguageChange) {
```
Comment (bjorn) [inline src/tiled/newversiondialog.cpp]: We don't need this in the `NewVersionDialog` because it is a modal dialog, so it's not possible to change the language while it is open.

File: src/tiled/propertieswidget.cpp [hunk 9]
```diff
@@ -3092,6 +3092,8 @@ bool PropertiesWidget::event(QEvent *event)
     }
     case QEvent::LanguageChange:
         retranslateUi();
+        if (mDocument)
+            currentObjectChanged(mDocument->currentObject());
```
Comment (bjorn) [inline src/tiled/propertieswidget.cpp]: Since you've already adjusted a bunch of widgets used in the properties view to handle `QEvent::LanguageChange`, is this really necessary?

File: src/tiled/shortcutsettingspage.cpp [hunk 10]
```diff
@@ -93,6 +94,11 @@ ActionsModel::ActionsModel(QObject *parent)
             this, &ActionsModel::actionChanged);
     connect(ActionManager::instance(), &ActionManager::actionsChanged,
             this, [this] { mDirty = mConflictsDirty = true; refresh(); });
+    connect(Preferences::instance(), &Preferences::languageChanged,
+            this, [this] {
+                emit headerDataChanged(Qt::Horizontal, 0, 2);
+                refresh();
+            });
```
Comment (bjorn) [inline src/tiled/shortcutsettingspage.cpp]: Please trigger this from `ShortcutSettingsPage` based on `QEvent::LanguageChange`.

File: src/tiled/stampactions.cpp [hunk 11]
```diff
@@ -76,6 +77,9 @@ StampActions::StampActions(QObject *parent) : QObject(parent)
 
     setEnabled(false);
     languageChanged();
+
+    connect(Preferences::instance(), &Preferences::languageChanged,
+            this, &StampActions::languageChanged);
```
Comment (bjorn) [inline src/tiled/stampactions.cpp]: This is already called from the various tools that use `StampActions`.

File: src/tiled/templatesdock.cpp [hunk 12]
```diff
@@ -64,6 +65,8 @@ TemplatesDock::TemplatesDock(QWidget *parent)
     , mRedoAction(new QAction(this))
     , mMapScene(new MapScene(this))
     , mMapView(new MapView(this))
+    , mObjectTemplate(nullptr)
+    , mPropertiesDock(nullptr)
```
Comment (bjorn) [inline src/tiled/templatesdock.cpp]: Good catch that these were not getting initialized! Just please move the initialization to the header file.

File: src/tiled/tilestampmodel.cpp [hunk 13]
```diff
@@ -21,12 +21,17 @@
...
 
 namespace Tiled {
 
 TileStampModel::TileStampModel(QObject *parent)
     : QAbstractItemModel(parent)
 {
+    connect(Preferences::instance(), &Preferences::languageChanged,
+            this, [this] {
+                emit headerDataChanged(Qt::Horizontal, 0, 1);
+            });
```
Comment (bjorn) [inline src/tiled/tilestampmodel.cpp]: Could we trigger this from `TileStampsDock::retranslateUi`?

**Review by bjorn — CHANGES_REQUESTED** [review]
Thanks for catching so many cases where strings were not getting updated! However, there are also many places covered which don't need to be:

* Popups and dialogs don't need this, because you can't change the language while they are open.
* In some cases, the strings were already getting updated through other means. This makes me wonder how you searched for missing cases.

And I'd like to avoid connecting to `Preferences::languageChanged` where possible, and I think it is basically always possible because in the end there's always a widget involved in displaying a string, which will get the `QEvent::LanguageChange`.

I see there were three existing cases of connecting to `languageChanged`, but I might look into changing those sooner or later because I think it doesn't set the best example. :-)

**Comment by SIDDHAARTHAA** [comment]
Thanks for the detailed feedback @bjorn , that makes sense.

You’re right that my initial sweep overreached. I started from a static search (`tr(...)`, constructor-set text/tooltips, model `headerData()/data()`), then added missing local hooks, but that did not sufficiently account for existing retranslation paths through parent widgets (like `MainWindow::retranslateUi`) and it also included popup/dialog cases that don’t need live updates.

I’ve now adjusted this to follow the pattern you described:
- removed the new direct `Preferences::languageChanged` connections,
- moved model refreshes behind widget-driven `QEvent::LanguageChange`,
- and dropped popup/dialog-only retranslation changes.

I’m currently testing the updated version and will commit/push shortly once verified.

File: src/tiled/brokenlinks.cpp (hunk 1 above)
Comment (SIDDHAARTHAA) [reply src/tiled/brokenlinks.cpp]: done

File: src/tiled/commanddatamodel.cpp (hunk 2 above)
Comment (SIDDHAARTHAA) [reply src/tiled/commanddatamodel.cpp]: done

**Review by bjorn — APPROVED** [review]
Thanks @SIDDHAARTHAA! I've submitted some additional tweaks, and I think this is ready to be merged now. :-)
