### PR TITLE
Fix Export As trailing dot when export filter is unset

### LINKED ISSUE #3520: Extension error in export function
"Export as..." puts two dots before file extension:

- filename..tsx
- filename..tsj

### PR DESCRIPTION
**Pull request by SIDDHAARTHAA**
closes #3520

Fixes `Export As...` generating filenames with a trailing dot when no export filter is available (e.g. unset session preference), which could lead to outputs like `name..tsx`.

Changes:
- In export filename suggestion, only append `.` + extension when the parsed extension is non-empty.
- Align tileset export filter session key to `tileset.lastUsedExportFilter` so the correct preference is reused.

### CODE REVIEW

File: src/tiled/mainwindow.cpp [hunk 1]
```diff
@@ -149,13 +149,13 @@ ExportDetails<Format> chooseExportDetails(const QString &fileName,
 
         QRegularExpression extensionFinder(QLatin1String("\\(\\*\\.([^\\)\\s]*)"));
         QRegularExpressionMatch match = extensionFinder.match(selectedFilter);
-        const QString extension = match.captured(1);
+        const QString extension = match.captured(1).trimmed();
```
Comment (bjorn) [inline src/tiled/mainwindow.cpp]:
```suggestion
        const QString extension = match.captured(1);
```
Let's not trim this because the capture in the regular expression already excludes whitespace.
