### PR TITLE
Fix snapping mode sync across instances

### LINKED ISSUE #3788: Multiple instances of Tiled can cause incorrect Snapping
When using the Offset Layers tool, it always snaps to the grid, regardless of the current Snapping setting. I think this tool should respect the current Snapping option.

For now, it's possible to work around this by adjusting the Offsets directly in the Layer Properties.

Observed in 1.10.1. I suspect this is a regression, though I don't use this tool often enough to have noticed when it happened. This was reported by a user on Discord.

### PR DESCRIPTION
**Pull request by SIDDHAARTHAA**
Closes #3788

This changes snapping preferences to use a single `Interface/SnapMode` enum instead of three separate boolean flags. Legacy `SnapToGrid` / `SnapToFineGrid` / `SnapToPixels` values are migrated on startup with the same priority behavior as before. The snapping menu now updates from `snapMode` consistently and refreshes on window activation / menu open, so multiple Tiled instances stay in sync with `tiled.conf`.

### CODE REVIEW

**Comment by SIDDHAARTHAA** [comment]
@bjorn Please review it whenever possible. I've tried my best to write good code :)
I have also rigorously tested it.

File: src/tiled/mainwindow.cpp [hunk 1]
```diff
@@ -412,6 +412,7 @@ MainWindow::MainWindow(QWidget *parent, Qt::WindowFlags flags)
             mTilesetEditor->templatesDock(), &TemplatesDock::tryOpenTemplate);
 
     auto snappingGroup = new QActionGroup(this);
+    snappingGroup->setExclusive(true);
```
Comment (bjorn) [inline src/tiled/mainwindow.cpp]: Exclusive is the default so we don't need this.

File: src/tiled/mainwindow.cpp [hunk 2]
```diff
@@ -564,12 +567,22 @@ MainWindow::MainWindow(QWidget *parent, Qt::WindowFlags flags)
...
+            preferences->setSnapMode(SnapMode::Grid);
+    });
+    connect(mUi->actionSnapToFineGrid, &QAction::toggled, preferences, [preferences](bool checked) {
+        if (checked)
+            preferences->setSnapMode(SnapMode::FineGrid);
+    });
+    connect(mUi->actionSnapToPixels, &QAction::toggled, preferences, [preferences](bool checked) {
+        if (checked)
+            preferences->setSnapMode(SnapMode::Pixels);
+    });
```
Comment (bjorn) [inline src/tiled/mainwindow.cpp:573]: Please instead of connecting to the `triggered` signal for each action, connect to the `QActionGroup::triggered` signal of the `actionGroup`.

To get the snap mode from the triggered action, you can do:
```c++
mUi->actionSnapNothing->setData(QVariant::fromValue(SnapMode::None));
```
And in the lambda handling the `triggered` signal:
```c++
connect(snappingGroup, &QActionGroup::triggered, preferences, [preferences](QAction *action) {
    preferences->setSnapMode(action->data().value<SnapMode>());
});
```

File: src/tiled/mainwindow.cpp [hunk 3]
```diff
@@ -423,11 +424,14 @@ MainWindow::MainWindow(QWidget *parent, Qt::WindowFlags flags)
...
     mUi->actionEnableParallax->setChecked(preferences->parallaxEnabled());
-    mUi->actionSnapToGrid->setChecked(preferences->snapToGrid());
-    mUi->actionSnapToFineGrid->setChecked(preferences->snapToFineGrid());
-    mUi->actionSnapToPixels->setChecked(preferences->snapToPixels());
+    updateSnappingActions(preferences->snapMode());
     mUi->actionHighlightCurrentLayer->setChecked(preferences->highlightCurrentLayer());
     mUi->actionHighlightHoveredObject->setChecked(preferences->highlightHoveredObject());
+    connect(preferences, &Preferences::snapModeChanged, this, &MainWindow::updateSnappingActions);
+    connect(mUi->menuSnapping, &QMenu::aboutToShow, this, [this, preferences] {
+        preferences->sync();
```
Comment (bjorn) [inline src/tiled/mainwindow.cpp]: This change adds three calls to `QSettings::sync` in various places, but its documentation says:

> This function is called automatically from QSettings's destructor and by the event loop at regular intervals, so you normally don't need to call it yourself.

So I don't think we need these?

File: src/tiled/mainwindow.cpp [hunk 4]
```diff
@@ -2016,6 +2031,19 @@ void MainWindow::autoMappingWarning(bool automatic)
     }
 }
 
+void MainWindow::updateSnappingActions(SnapMode mode)
+{
+    const QSignalBlocker blockSnapNothing(mUi->actionSnapNothing);
+    const QSignalBlocker blockSnapToGrid(mUi->actionSnapToGrid);
+    const QSignalBlocker blockSnapToFineGrid(mUi->actionSnapToFineGrid);
+    const QSignalBlocker blockSnapToPixels(mUi->actionSnapToPixels);
```
Comment (bjorn) [inline src/tiled/mainwindow.cpp]: If you connect to `triggered` instead of `toggled`, you don't need to use signal blockers because the `triggered` signal is only emitted as a result of user interaction.

File: src/tiled/mainwindow.cpp [hunk 5]
```diff
@@ -965,6 +978,13 @@ void MainWindow::changeEvent(QEvent *event)
     case QEvent::WindowStateChange:
         mUi->actionFullScreen->setChecked(isFullScreen());
         break;
+    case QEvent::ActivationChange:
+        if (isActiveWindow()) {
+            Preferences *preferences = Preferences::instance();
+            preferences->sync();
+            updateSnappingActions(preferences->snapMode());
```
Comment (bjorn) [inline src/tiled/mainwindow.cpp]: Since you're already calling this on `QMenu::aboutToShow`, I don't think we gain anything by also doing it on `ActivationChange` and I think we can also remove the direct call from the `MainWindow` constructor.

**Review by bjorn — CHANGES_REQUESTED** [review]
Thanks for fixing this issue, @SIDDHAARTHAA! I've pushed a bunch of cleanups of stuff you left around which was no longer used and changed `SnapHelper` to use the same enum because it was a bit strange how it still had "snap to pixels" as separate boolean.

But I've also left some comments for you to address! :-)

**Comment by SIDDHAARTHAA** [comment]
Thanks for the review! I addressed all requested points: removed explicit action group exclusivity, switched snap handling to `QActionGroup::triggered` using action `data()` for `SnapMode`, removed manual `QSettings::sync()` calls, removed signal blockers, and dropped the `ActivationChange` refresh path.

File: src/tiled/mainwindow.cpp (hunk 3 above)
Comment (SIDDHAARTHAA) [reply src/tiled/mainwindow.cpp]: okayy

File: src/tiled/mainwindow.cpp [hunk 6]
```diff
@@ -416,18 +415,23 @@ MainWindow::MainWindow(QWidget *parent, Qt::WindowFlags flags)
...
     mUi->actionShowObjectReferences->setChecked(preferences->showObjectReferences());
     mUi->actionShowTileAnimations->setChecked(preferences->showTileAnimations());
     mUi->actionShowTileCollisionShapes->setChecked(preferences->showTileCollisionShapes());
     mUi->actionEnableParallax->setChecked(preferences->parallaxEnabled());
-    mUi->actionSnapToGrid->setChecked(preferences->snapToGrid());
-    mUi->actionSnapToFineGrid->setChecked(preferences->snapToFineGrid());
-    mUi->actionSnapToPixels->setChecked(preferences->snapToPixels());
     mUi->actionHighlightCurrentLayer->setChecked(preferences->highlightCurrentLayer());
     mUi->actionHighlightHoveredObject->setChecked(preferences->highlightHoveredObject());
+    connect(preferences, &Preferences::snapModeChanged, this, &MainWindow::updateSnappingActions);
```
Comment (bjorn) [inline src/tiled/mainwindow.cpp]: I think we also don't need this connection, since we're always calling `updateSnappingActions` when the menu opens anyway.

**Comment by bjorn** [comment]
Thanks @SIDDHAARTHAA!

**Comment by SIDDHAARTHAA** [comment]
My pleasure ;)
